# Config data exposed by config server
info:
  foo: ttsgw-default
  someList: [2, 3, 7]
aaaaaaa: cccccccccccccccccc

---
spring:
  profiles: cloud
sftp:
  host: home.open-rate.com 
  use-password: true
  user: shaun
  password: strongxxxpassword
  port: 22
  remote-path: .
  delete-file-after-transfer: true

---
spring:
  profiles: unit-test
info:
  foo: ttsgw-unit-test
